FROM ubuntu:14.04
FROM rioualen/ubuntu-essentials:1.0
FROM rioualen/python-essentials:1.0

RUN pip install MACS2

ENV PATH $PATH:/usr/local/bin

MAINTAINER Claire Rioualen <claire.rioualen@inserm.fr>
