FROM ubuntu:14.04

RUN apt-get update && \
    apt-get -y install ssh \
    rsync \
    git \
    graphviz \
    gedit-plugins \
    wget \
    nano \
    zlibc \
    zlib1g-dev \
    build-essential \
    libncurses5-dev \
    libncursesw5-dev \
    libboost-dev \
    gdebi \
    software-properties-common \
    unzip \
    zip

MAINTAINER Claire Rioualen <claire.rioualen@inserm.fr>
